# Makefile generated by genmake.pl
# Written by Ramo

CC=g++
BUILD=build
DIST=dist
CCFLAGS=-c -g -Weverything -Wno-disabled-macro-expansion -Wno-padded -Wno-weak-vtables
LDFLAGS=-o $(DIST)/prog -lpthread 

all:	$(DIST)/prog
$(DIST)/prog:	$(BUILD) $(DIST) $(BUILD)/screenLayout.o $(BUILD)/mpdConn.o $(BUILD)/main.o 
	$(CC) $(BUILD)/*.o $(LDFLAGS)
$(BUILD)/screenLayout.o:	screenLayout.cpp screenLayout.h
	$(CC) screenLayout.cpp $(CCFLAGS) -o $(BUILD)/screenLayout.o
$(BUILD)/mpdConn.o:	mpdConn.cpp mpdConn.h
	$(CC) mpdConn.cpp $(CCFLAGS) -o $(BUILD)/mpdConn.o
$(BUILD)/main.o:	main.cpp mpdConn.h screenLayout.h
	$(CC) main.cpp $(CCFLAGS) -o $(BUILD)/main.o
$(BUILD):
	@mkdir $(BUILD)
$(DIST):
	@mkdir $(DIST)
clean:
	rm -rf $(BUILD) $(DIST)
love:
	@echo Not war
